name: Build
on:
  push:
  pull_request:
  create:
    tags:
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: qutest
            asset_name: qutest-x86_64-linux
          - os: macos-latest
            artifact_name: qutest
            asset_name: qutest-x86_64-apple-darwin
          - os: windows-latest
            artifact_name: qutest.exe
            asset_name: qutest-x86_64-windows.exe
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - uses: actions/checkout@v3
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        if: matrix.os != 'windows-latest'
        run: go test -v ./...
      - name: Smoke Test
        run: ./qutest tests/should_pass.js tests/a_typescript_file.ts
      - name: Release
        uses: svenstaro/upload-release-action@2.5.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.ref }}
