name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - uses: actions/checkout@v3
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Success Test
        run: ./qutest tests/should_pass.js tests/a_typescript_file.ts
